"""replace category columns with classifications array

Revision ID: 58a93e41a81b
Revises: 730a72e55f85
Create Date: 2026-05-19 09:52:00.309651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '58a93e41a81b'
down_revision: Union[str, Sequence[str], None] = '730a72e55f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('classifications', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.drop_index(op.f('idx_actions_category'), table_name='actions')
    op.create_index('idx_actions_classifications', 'actions', ['classifications'], unique=False, postgresql_using='gin')
    op.drop_column('actions', 'sub_category')
    op.drop_column('actions', 'category')
    op.drop_index(op.f('idx_embeddings_vector'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_embeddings_vector'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('actions', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('actions', sa.Column('sub_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index('idx_actions_classifications', table_name='actions', postgresql_using='gin')
    op.create_index(op.f('idx_actions_category'), 'actions', ['site_id', 'category'], unique=False)
    op.drop_column('actions', 'classifications')
    # ### end Alembic commands ###
