"""create initial schema

Revision ID: 730a72e55f85
Revises:
Create Date: 2026-05-18 22:59:00.454251

"""

import sqlalchemy as sa
import pgvector.sqlalchemy
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "730a72e55f85"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("wp_post_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=True),
        sa.Column("steps_to_take_html", sa.Text(), nullable=True),
        sa.Column("steps_to_take_text", sa.Text(), nullable=True),
        sa.Column("deep_dive_html", sa.Text(), nullable=True),
        sa.Column("deep_dive_text", sa.Text(), nullable=True),
        sa.Column("is_featured", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("sub_category", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "wp_post_id", name="uq_actions_site_post"),
    )
    op.create_index(
        "idx_actions_category", "actions", ["site_id", "category"], unique=False
    )
    op.create_index(op.f("ix_actions_site_id"), "actions", ["site_id"], unique=False)
    op.create_table(
        "embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False
        ),
        sa.Column("embedding_model", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "content_type",
            "content_id",
            "chunk_index",
            name="uq_embeddings_content_chunk",
        ),
    )
    op.execute("""
    CREATE INDEX idx_embeddings_vector
    ON embeddings
    USING hnsw (embedding vector_cosine_ops)
""")
    op.create_index(
        op.f("ix_embeddings_content_type"), "embeddings", ["content_type"], unique=False
    )
    op.create_index(
        op.f("ix_embeddings_site_id"), "embeddings", ["site_id"], unique=False
    )
    op.create_table(
        "events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("wp_post_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description_html", sa.Text(), nullable=True),
        sa.Column("description_text", sa.Text(), nullable=True),
        sa.Column("start_datetime_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_datetime_utc", sa.DateTime(timezone=True), nullable=True),
        sa.Column("start_datetime_local", sa.DateTime(), nullable=True),
        sa.Column("end_datetime_local", sa.DateTime(), nullable=True),
        sa.Column("timezone", sa.String(), nullable=True),
        sa.Column("venue_name", sa.String(), nullable=True),
        sa.Column("venue_address", sa.String(), nullable=True),
        sa.Column("organizer_names", sa.String(), nullable=True),
        sa.Column("organizer_emails", sa.String(), nullable=True),
        sa.Column("event_url", sa.String(), nullable=True),
        sa.Column("cost", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "wp_post_id", name="uq_events_site_post"),
    )
    op.create_index(
        "idx_events_upcoming", "events", ["site_id", "start_datetime_utc"], unique=False
    )
    op.create_index(op.f("ix_events_site_id"), "events", ["site_id"], unique=False)
    op.create_table(
        "testimonials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("wp_post_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("body_html", sa.Text(), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=True),
        sa.Column("submitted_by", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("related_action_wp_post_id", sa.Integer(), nullable=True),
        sa.Column("related_action_id", sa.UUID(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_action_id"], ["actions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "wp_post_id", name="uq_testimonials_site_post"),
    )
    op.create_index(
        "idx_testimonials_action", "testimonials", ["related_action_id"], unique=False
    )
    op.create_index(
        op.f("ix_testimonials_site_id"), "testimonials", ["site_id"], unique=False
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_testimonials_site_id"), table_name="testimonials")
    op.drop_index("idx_testimonials_action", table_name="testimonials")
    op.drop_table("testimonials")
    op.drop_index(op.f("ix_events_site_id"), table_name="events")
    op.drop_index("idx_events_upcoming", table_name="events")
    op.drop_table("events")
    op.drop_index(op.f("ix_embeddings_site_id"), table_name="embeddings")
    op.drop_index(op.f("ix_embeddings_content_type"), table_name="embeddings")
    op.drop_table("embeddings")
    op.execute("DROP INDEX IF EXISTS idx_embeddings_vector")
    op.drop_index(op.f("ix_actions_site_id"), table_name="actions")
    op.drop_index("idx_actions_category", table_name="actions")
    op.drop_table("actions")

    # ### end Alembic commands ###
