"""add archived_at to content tables

Revision ID: a17c58cc50c2
Revises: 58a93e41a81b
Create Date: 2026-05-19 11:37:16.068324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a17c58cc50c2'
down_revision: Union[str, Sequence[str], None] = '58a93e41a81b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('events', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('testimonials', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'archived_at')
    op.drop_column('events', 'archived_at')
    op.drop_column('actions', 'archived_at')
    # ### end Alembic commands ###
