"""add image_url to actions testimonials events

Revision ID: b4bd5da58f63
Revises: b027570156bb
Create Date: 2026-05-20 01:23:15.399996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4bd5da58f63'
down_revision: Union[str, Sequence[str], None] = 'b027570156bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actions', sa.Column('image_url', sa.String(), nullable=True))
    op.drop_index(op.f('idx_embeddings_vector'), table_name='embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('testimonials', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testimonials', 'image_url')
    op.drop_column('events', 'image_url')
    op.create_index(op.f('idx_embeddings_vector'), 'embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('actions', 'image_url')
    # ### end Alembic commands ###
